// Sample Village Partner Network data.
// Structure mirrors the API shape described in the design handoff README
// (GET /api/partners). Replace with a real fetch() once a backend exists.

const PARTNERS = [
  {
    id: 'pillar-pelvic-health',
    practiceName: 'Pillar Pelvic Health',
    providerName: 'Dr. Sarah Jenkins',
    credentials: 'PT, DPT',
    initials: 'SJ',
    category: 'Pelvic Health',
    categoryTag: 'Pelvic Health & Postpartum',
    neighborhoods: ['Hyde Park', 'Oakley'],
    neighborhoodGroup: 'Hyde Park / Oakley',
    bio: 'Specialized care for pregnant and postpartum bodies. Prenatal preparation, diastasis recti recovery, and pelvic floor rehabilitation in a warm, community-centered practice.',
    website: '',
    phone: '513-892-3456',
    email: 'sarah@pillar.local',
    idealClientProfile: 'Pregnant mommas 28+ weeks, postpartum recovery',
    referralTriggers: 'Pelvic pain, incontinence, diastasis recti, painful intercourse',
    referOutFor: 'Pediatric PT, lactation support, OB-GYN',
    verified: true,
  },
  {
    id: 'bright-minds-tutoring',
    practiceName: 'Bright Minds Tutoring',
    providerName: 'Jennifer Liu',
    credentials: 'M.Ed',
    initials: 'JL',
    category: 'Tutors & Educators',
    categoryTag: 'Tutors & Educators',
    neighborhoods: ['Montgomery', 'Indian Hill'],
    neighborhoodGroup: 'Montgomery / Indian Hill',
    bio: 'Personalized academic support for elementary through high school. Specializing in reading intervention, executive function coaching, and gifted student enrichment.',
    website: '',
    phone: '513-654-9801',
    email: 'jen@brightminds.local',
    idealClientProfile: 'Elementary & middle school students, gifted track',
    referralTriggers: 'Reading intervention, executive function coaching, SAT prep',
    referOutFor: 'Speech therapy, educational psychology, private schools',
    verified: true,
  },
  {
    id: 'anchor-family-law',
    practiceName: 'Anchor Family Law',
    providerName: 'Rebecca Cohen',
    credentials: 'Esq.',
    initials: 'RC',
    category: 'Family Law',
    categoryTag: 'Family Law',
    neighborhoods: ['East Walnut Hills', 'Clifton'],
    neighborhoodGroup: 'East Walnut Hills / Clifton',
    bio: 'Compassionate legal guidance for families navigating custody, co-parenting, and divorce. Trauma-informed approach that prioritizes children and co-parenting success.',
    website: '',
    phone: '513-445-2211',
    email: 'rebecca@anchorfamily.local',
    idealClientProfile: 'Parents navigating custody, co-parenting post-divorce',
    referralTriggers: 'Custody disputes, high-conflict co-parenting, family mediation',
    referOutFor: 'Therapists, financial advisors, custody evaluators',
    verified: true,
  },
  {
    id: 'root-and-rise-lactation',
    practiceName: 'Root & Rise Lactation',
    providerName: 'Marcus & Elena Davis',
    credentials: '',
    initials: 'ED',
    category: 'Postpartum & Lactation',
    categoryTag: 'Postpartum & Lactation',
    neighborhoods: ['Mariemont', 'Newtown'],
    neighborhoodGroup: 'Mariemont / Newtown',
    bio: 'Holistic feeding support for new families. Whether breastfeeding, formula feeding, or combination feeding — evidence-based care without judgment.',
    website: '',
    phone: '513-721-5544',
    email: 'help@rootandrise.local',
    idealClientProfile: 'Postpartum parents, breastfeeding & formula feeding support',
    referralTriggers: 'Latch dysfunction, supply issues, weaning support',
    referOutFor: 'OB-GYN, pediatrics, pelvic health, doulas',
    verified: true,
  },
];

const NEIGHBORHOOD_PILLS = [
  'All',
  'Hyde Park / Oakley',
  'Montgomery / Indian Hill',
  'East Walnut Hills / Clifton',
  'Mariemont / Newtown',
];

const CATEGORY_OPTIONS = [
  'All Specialties',
  'Pelvic Health',
  'Pediatric Dentistry',
  'Family Law',
  'Postpartum & Lactation',
  'Tutors & Educators',
];
